//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XEP_SectionCheckCommon.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XEP_SectionCheckCommon.Res.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B#.
        /// </summary>
        public static string B_MARK {
            get {
                return ResourceManager.GetString("B_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B@hole#.
        /// </summary>
        public static string Bhole_MARK {
            get {
                return ResourceManager.GetString("Bhole_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram type#.
        /// </summary>
        public static string DiagramType_MARK {
            get {
                return ResourceManager.GetString("DiagramType_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ε@c1#.
        /// </summary>
        public static string EpsC1_MARK {
            get {
                return ResourceManager.GetString("EpsC1_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ε@c2#.
        /// </summary>
        public static string EpsC2_MARK {
            get {
                return ResourceManager.GetString("EpsC2_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ε@c3#.
        /// </summary>
        public static string EpsC3_MARK {
            get {
                return ResourceManager.GetString("EpsC3_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ε@cu1#.
        /// </summary>
        public static string EpsCu1_MARK {
            get {
                return ResourceManager.GetString("EpsCu1_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ε@cu2#.
        /// </summary>
        public static string EpsCu2_MARK {
            get {
                return ResourceManager.GetString("EpsCu2_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ε@cu3#.
        /// </summary>
        public static string EpsCu3_MARK {
            get {
                return ResourceManager.GetString("EpsCu3_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F@ck#.
        /// </summary>
        public static string Fck_MARK {
            get {
                return ResourceManager.GetString("Fck_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F@ck,Cube#.
        /// </summary>
        public static string FckCube_MARK {
            get {
                return ResourceManager.GetString("FckCube_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H#.
        /// </summary>
        public static string H_MARK {
            get {
                return ResourceManager.GetString("H_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H@hole#.
        /// </summary>
        public static string Hhole_MARK {
            get {
                return ResourceManager.GetString("Hhole_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hole mode#.
        /// </summary>
        public static string HoleMode_MARK {
            get {
                return ResourceManager.GetString("HoleMode_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material name#.
        /// </summary>
        public static string MaterialName_MARK {
            get {
                return ResourceManager.GetString("MaterialName_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material from library#.
        /// </summary>
        public static string MatFromLibMode_MARK {
            get {
                return ResourceManager.GetString("MatFromLibMode_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N#.
        /// </summary>
        public static string N_MARK {
            get {
                return ResourceManager.GetString("N_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon mode#.
        /// </summary>
        public static string PolygonMode_MARK {
            get {
                return ResourceManager.GetString("PolygonMode_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fucekr.
        /// </summary>
        public static string Y_MARK {
            get {
                return ResourceManager.GetString("Y_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z#.
        /// </summary>
        public static string Z_MARK {
            get {
                return ResourceManager.GetString("Z_MARK", resourceCulture);
            }
        }
    }
}
