//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XEP_CssProperties.ResTrans {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XEP_CssProperties.ResTrans.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ADD {
            get {
                return ResourceManager.GetString("ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add material to library.
        /// </summary>
        public static string ADD_MAT_TO_LIB {
            get {
                return ResourceManager.GetString("ADD_MAT_TO_LIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string COPY {
            get {
                return ResourceManager.GetString("COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Section.
        /// </summary>
        public static string CROSS_SECTION {
            get {
                return ResourceManager.GetString("CROSS_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete material from library.
        /// </summary>
        public static string DELETE_MAT_FROM_LIB {
            get {
                return ResourceManager.GetString("DELETE_MAT_FROM_LIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to εc₁ explanation.
        /// </summary>
        public static string EPS_C1_EXPL {
            get {
                return ResourceManager.GetString("EPS_C1_EXPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to εc₁.
        /// </summary>
        public static string EPS_C1_MARK {
            get {
                return ResourceManager.GetString("EPS_C1_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to εc₂ explanation.
        /// </summary>
        public static string EPS_C2_EXPL {
            get {
                return ResourceManager.GetString("EPS_C2_EXPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to εc₂.
        /// </summary>
        public static string EPS_C2_MARK {
            get {
                return ResourceManager.GetString("EPS_C2_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to εc₃ explanation.
        /// </summary>
        public static string EPS_C3_EXPL {
            get {
                return ResourceManager.GetString("EPS_C3_EXPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to εc₃.
        /// </summary>
        public static string EPS_C3_MARK {
            get {
                return ResourceManager.GetString("EPS_C3_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to εcu₁ explanation.
        /// </summary>
        public static string EPS_CU1_EXPL {
            get {
                return ResourceManager.GetString("EPS_CU1_EXPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to εcu₁.
        /// </summary>
        public static string EPS_CU1_MARK {
            get {
                return ResourceManager.GetString("EPS_CU1_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to εcu₂ explanation.
        /// </summary>
        public static string EPS_CU2_EXPL {
            get {
                return ResourceManager.GetString("EPS_CU2_EXPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to εcu₂.
        /// </summary>
        public static string EPS_CU2_MARK {
            get {
                return ResourceManager.GetString("EPS_CU2_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to εcu₃ explanation.
        /// </summary>
        public static string EPS_CU3_EXPL {
            get {
                return ResourceManager.GetString("EPS_CU3_EXPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to εcu₃.
        /// </summary>
        public static string EPS_CU3_MARK {
            get {
                return ResourceManager.GetString("EPS_CU3_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fck cube explanation.
        /// </summary>
        public static string FCK_CUBE_EXPL {
            get {
                return ResourceManager.GetString("FCK_CUBE_EXPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FckCube.
        /// </summary>
        public static string FCK_CUBE_MARK {
            get {
                return ResourceManager.GetString("FCK_CUBE_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fck explantion.
        /// </summary>
        public static string FCK_EXPL {
            get {
                return ResourceManager.GetString("FCK_EXPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fck.
        /// </summary>
        public static string FCK_MARK {
            get {
                return ResourceManager.GetString("FCK_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry.
        /// </summary>
        public static string GEOMETRY {
            get {
                return ResourceManager.GetString("GEOMETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Forces.
        /// </summary>
        public static string INTERNAL_FORCES {
            get {
                return ResourceManager.GetString("INTERNAL_FORCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library material.
        /// </summary>
        public static string MAT_FROM_LIB {
            get {
                return ResourceManager.GetString("MAT_FROM_LIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material properties - .
        /// </summary>
        public static string MAT_PROP {
            get {
                return ResourceManager.GetString("MAT_PROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material specification.
        /// </summary>
        public static string MATERIAL_SPECIFICATION {
            get {
                return ResourceManager.GetString("MATERIAL_SPECIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N explanation.
        /// </summary>
        public static string N_EXPL {
            get {
                return ResourceManager.GetString("N_EXPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string N_MARK {
            get {
                return ResourceManager.GetString("N_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string PARAMETERS {
            get {
                return ResourceManager.GetString("PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string PASTE {
            get {
                return ResourceManager.GetString("PASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string PROPERTIES {
            get {
                return ResourceManager.GetString("PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TYPE {
            get {
                return ResourceManager.GetString("TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string VALUE {
            get {
                return ResourceManager.GetString("VALUE", resourceCulture);
            }
        }
    }
}
