//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XEP_SectionCheckCommon.ResTrans {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XEP_SectionCheckCommon.ResTrans.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilinear for ULS.
        /// </summary>
        public static string BILI_ULS {
            get {
                return ResourceManager.GetString("BILI_ULS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear without tension,Ec=Eceff.
        /// </summary>
        public static string LIN_ECFF {
            get {
                return ResourceManager.GetString("LIN_ECFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear without tension,Ec=Ecm.
        /// </summary>
        public static string LIN_ECM {
            get {
                return ResourceManager.GetString("LIN_ECM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear with tension, Ec=Eceff.
        /// </summary>
        public static string LIN_TEN_ECFF {
            get {
                return ResourceManager.GetString("LIN_TEN_ECFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear with tension, Ec=Ecm.
        /// </summary>
        public static string LIN_TEN_ECM {
            get {
                return ResourceManager.GetString("LIN_TEN_ECM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parabola-rectangular for ULS.
        /// </summary>
        public static string PAR_RECT_ULS {
            get {
                return ResourceManager.GetString("PAR_RECT_ULS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User diagram.
        /// </summary>
        public static string USER_DIAGRAM {
            get {
                return ResourceManager.GetString("USER_DIAGRAM", resourceCulture);
            }
        }
    }
}
